apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/app
  - namespace.yaml

components:
  - ../../common/dev/mongo-connection-data

secretGenerator:
  - name: proxy-url
    behavior: replace
    literals:
      - url=https://libretranslate.com/translate

namespace: dev