apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

secretGenerator:
  - name: mongo-connection-data
    behavior: merge
    literals:
      - MONGO_ADMIN_USER=root
      - MONGO_ADMIN_PASSWORD=securePassw0rd